# https://dev.to/sonyarianto/how-to-spin-mongodb-server-with-docker-and-docker-compose-2lef
version: '3.4'

services:
  mongo:
      image: mongo:latest
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db
  classregistrar:
    depends_on:
      - mongo
    image: ${DOCKER_REGISTRY-}classregistrar
    environment:
      MongoDB__Host: mongo
    build:
      context: .
      dockerfile: ClassRegistrar/Dockerfile
volumes:
  mongodb_data_container:
